### ISSUE TITLE
Extension throws error and hangs indefinitely

### ISSUE THREAD

**Issue by mulligancb** [vignaesh01/sfdx-package-generator#1]
Hi, I am not sure if this is the right place to post this, but I noticed that the generator was never completing.  After looking into the developer console in VSCode it looks like it is erroring out parsing the JSON.

[packagegenerator.log](https://github.com/vignaesh01/sfdx-package-generator/files/3164868/packagegenerator.log)

I am not sure that this isn't a configuration issue on my side, but I have been checking for hours, reinstalling, etc. with no luck.  Thanks!

**Comment by vignaesh01** [comment]
Hi Mulligancb,
It seems to be an auth error. Before using this extension you need to create a sfdx project with manifest and Authorize it using commands in salesforce extension for vs code suite. This extension works only for org based development model
Refer : https://forcedotcom.github.io/salesforcedx-vscode/articles/user-guide/org-development-model

**Comment by vignaesh01** [comment]
If you have already done the above steps, try re authorizing your org using SFDX: Authorize an Org

**Comment by vignaesh01** [comment]
The fix for this issue has been pushed as part of the latest 0.0.10 patch version of the extension. Please update and let me know whether it works now.

**Comment by mulligancb** [comment]
Thank you.  That worked like a charm.   Cool plugin!

**Comment by vignaesh01** [comment]
Thank you
