### ISSUE TITLE
Salesforce retrieval through generated package.xml retrieves part of the file

### ISSUE THREAD

**Issue by cbsp101** [vignaesh01/sfdx-package-generator#10]
On VSCode, when tried to retrieve profiles from a salesforce org, 2 issues are encountered:

Issue 1: when retrieved the profiles via sfdx Package.xml generator:Choose metadata components around 300+ lines of the file were missing from the retrieved file

Issue 2: The sequence of code lines are changed while retrieve from Salesforce sandbox

**Comment by tet3** [comment]
This is still not the right place to report this issue @cbsp101 - all the package.xml generator does is, well, generate the package.xml. The retrieval of the metadata specified in the package.xml is done by sfdx. If this is actually a bug, then the place to report it is on the [forcedotcom/cli](https://github.com/forcedotcom/cli/issues) repo.

**Comment by cbsp101** [comment]
Thank you, have raised https://github.com/forcedotcom/cli/issues/139
