### ISSUE TITLE
The below error comes whenever the extension is initialized and nothing comes up in the Metadata Types dropdown

### ISSUE THREAD

**Issue by sud5792** [vignaesh01/sfdx-package-generator#121]
The below error comes whenever the extension is initialized :

**C:\Program Files\sf\client\node_modules\@salesforce\plugin-org\node_modules\@oclif\core\lib\cli-ux\index.js:30 const chalk_1 = __importDefault(require("chalk")); ^ Error [ERR_REQUIRE_ESM]: require() of ES Module C:\Program Files\sf\client\node_modules\@salesforce\plugin-org\node_modules\chalk\source\index.js from C:\Program Files\sf\client\node_modules\@salesforce\plugin-org\node_modules\@oclif\core\lib\cli-ux\index.js not supported. Instead change the require of C:\Program Files\sf\client\node_modules\@salesforce\plugin-org\node_modules\chalk\source\index.js in C:\Program Files\sf\client\node_modules\@salesforce\plugin-org\node_modules\@oclif\core\lib\cli-ux\index.js to a dynamic import() which is available in all CommonJS modules. at Object.<anonymous> (C:\Program Files\sf\client\node_modules\@salesforce\plugin-org\node_modules\@oclif\core\lib\cli-ux\index.js:30:33) { code: 'ERR_REQUIRE_ESM' } Node.js v20.10.0**

**Comment by vignaesh01** [comment]
@sud5792  - please try updating Salesforce CLI. Seems to be an issue with the CLI installation.
Update Salesforce CLI: npm install -g @salesforce/cli
