### ISSUE TITLE
/bin/sh: 1: sfdx: not found

### ISSUE THREAD

**Issue by m-lp-ql-m** [vignaesh01/sfdx-package-generator#122]
When clicking on SELECT ALL, this error appears in VS Code.

![Screenshot_20240906_102139](https://github.com/user-attachments/assets/152aad43-c9c2-4d15-918f-e0ea3e5b1ac8)

Both 'sf' and 'sfdx' at the command line work, so it does appear to be in my path.

EDIT: I should probably add: fresh install of Kubuntu 24.04.1

 CLI Version:
        @salesforce/cli/2.57.7 published 8 days ago (Wed Aug 28 2024)

 Architecture:
        linux-x64

 Node Version:
        node-v20.17.0

 Plugin Version:
        @oclif/plugin-autocomplete 3.2.2 (core)
        @oclif/plugin-commands 4.0.13 (core)
        @oclif/plugin-help 6.2.10 (core)
        @oclif/plugin-not-found 3.2.18 (core)
        @oclif/plugin-plugins 5.4.6 (core)
        @oclif/plugin-search 1.2.7 (core)
        @oclif/plugin-update 4.5.5 (core)
        @oclif/plugin-version 2.2.11 (core)
        @oclif/plugin-warn-if-update-available 3.1.13 (core)
        @oclif/plugin-which 3.2.12 (core)
        @salesforce/cli 2.57.7 (core)
        apex 3.4.5 (core)
        api 1.2.1 (core)
        auth 3.6.51 (core)
        data 3.6.3 (core)
        deploy-retrieve 3.12.0 (core)
        info 3.4.2 (core)
        limits 3.3.27 (core)
        marketplace 1.2.24 (core)
        org 4.5.4 (core)
        packaging 2.8.0 (core)
        schema 3.3.26 (core)
        settings 2.3.15 (core)
        sobject 1.4.32 (core)
        source 3.5.16 (core)
        telemetry 3.6.10 (core)
        templates 56.3.14 (core)
        trust 3.7.25 (core)
        user 3.5.26 (core)

 OS and Version:
        Linux 6.8.0-41-lowlatency

 Shell:
        bash

 Root Path:
        /home/mark/.nvm/versions/node/v20.17.0/lib/node_modules/@salesforce/cli

**Comment by MarcTCruz** [comment]
Same problem on Debian 12.

which sfdx
/home/mtpc/.nvm/versions/node/v20.17.0/bin/sfdx

Just fresh installed with npm install -g @salesforce/cli, also I had it working through a script I did using manual installation as well with the same problem.

**Comment by ujjwalverma55** [comment]
I am encountering the same issue in VS Code. Can anyone provide a solution?

**Comment by m-lp-ql-m** [comment]
@ujjwalverma55 Details? Which OS? "which sfdx"?

**Comment by vignaesh01** [comment]
@m-lp-ql-m @ujjwalverma55 - Can you try the latest 2.1.0 version?

**Comment by m-lp-ql-m** [comment]
@vignaesh01 On 2.1.0 now, _nothing_ happens. Just nothing.

I tried reinstalling the previous version, restarting VS Code, which produced the same error above, then reinstalling 2.1.0, restarting VS Code, and still, nothing.

FYI, likely unrelated, but I do have this other issue open with SFDX that's still unresolved: https://github.com/forcedotcom/salesforcedx-vscode/issues/5800

**Comment by vignaesh01** [comment]
Yes. It is related. The vs code extension depends on SF cli being properly
setup. Are you behind any corporate firewall?
Thanks,
Vignaesh Ram A

**Comment by m-lp-ql-m** [comment]
No firewall, this is on my home Linux computer. When I'm back in the office on 6 Jan, I'll verify on my work Windows 11 computer that it does work behind the corp firewall--I _think_ it was.

**Comment by vignaesh01** [comment]
I think it is related to your sf cli setup in your linux machine.
Thanks,
Vignaesh Ram A
