### ISSUE TITLE
'sfdx' is not recognized as an internal or external command, operable program or batch file. -- With new Sf CLI

### ISSUE THREAD

**Issue by BabunDey** [vignaesh01/sfdx-package-generator#123]
I am currently using @salesforce/cli/2.58.7 win32-x64 node-v20.17.0 and my path variable is also correct. Whenever I launch package.xml generator, it throws the error "'sfdx' is not recognized as an internal or external command, operable program or batch file"
<img width="960" alt="image" src="https://github.com/user-attachments/assets/4b5e2ab6-569d-47df-93c7-1f43440a763b">

**Comment by nicjames919** [comment]
I'm getting the same error as well today. Worked fine for me a few weeks ago

**Comment by mauriciomoita** [comment]
I think this is related to the move from sfdx to sf
Something probably needs to change on this project to start working with sf instead of sfdx...

**Comment by nicjames919** [comment]
It could’ve been. I ended up completely removing vs code, my local projects, and SF CLI and started fresh installs from scratch and a new project. Seems to be working fine so far.

**Comment by mauriciomoita** [comment]
Indeed! I'm with a fresh laptop and I just tried and it is working fine now!

**Comment by vignaesh01** [comment]
This issue should be fixed in version 2.1.0.
