### ISSUE TITLE
getting error while using this plugin

### ISSUE THREAD

**Issue by abdallammohd** [vignaesh01/sfdx-package-generator#126]
getting error while trying to pull metadata from Salesforce. it really doesnt affect the pull but its more of warning

(node:62967) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead. (Use `node --trace-deprecation ...` to show where the warning was created)

**Comment by RainnerCriticalRiver** [comment]
I'm having the same issue @abdallammohd, did you manage how to fix it?

**Comment by abdallammohd** [comment]
Nope.. but the component loads out perfectly fine. It seems its deprecation
/ dependency issue than functional issue.. i can live with that :)

**Comment by RainnerCriticalRiver** [comment]
Glad to hear that works out for you, I am still unable to access the metadata.

**Comment by benji1304** [comment]
Same issue and i can't get it to return any metadata

@vignaesh01 are you aware of this problem?

**Comment by vignaesh01** [comment]
Fixed.
