### ISSUE TITLE
I am getting the error "ERROR running force:source:retrieve:  Cannot read property 'metadataName' of undefined" When i choosed select ALL option on the components for package.xml page.

### ISSUE THREAD

**Issue by PreethiThotaMednax** [vignaesh01/sfdx-package-generator#13]
I ran sfdx update. This is the result what got : sfdx-cli: Updating CLI... already on latest version: 7.25.3-16d54c01ee
This is the version of the VS Code I am using: 1.38.1(User Setup)
Please Suggest.

**Comment by PreethiThotaMednax** [comment]
Hi Vignaesh,
Please help me understand how to get you the logs ?

Thank you

**Comment by PreethiThotaMednax** [comment]
Hi Vignaesh,
I would like to be more specific with the error details.
I am authorized to my developer sandbox.
I updated my package.xml using the Select All button.
Then when I retrieve source in the manifest from org I am getting the below error:
ERROR running force:source:retrieve:  Cannot read property 'metadataName' of undefined

Please find the log attached.
[Log.log](https://github.com/vignaesh01/sfdx-package-generator/files/3648760/Log.log)

**Comment by vignaesh01** [comment]
Hi Preethi,
 Since you are getting the error while running force:source:retrieve, please raise an issue under https://github.com/forcedotcom/salesforcedx-vscode . Please have faced similar issues and have raised it there.

As a quick fix, remove unnecessary metadata entries  from your package.xml file.

Hope this helps.

**Comment by PreethiThotaMednax** [comment]
Hi,
Thank you.
I ran the command sfdx force:mdapi:retrieve and was able to retrieve without any issues.
