### ISSUE TITLE
Can I use this extension to generate package xml for my production org? 

### ISSUE THREAD

**Issue by PreethiThotaMednax** [vignaesh01/sfdx-package-generator#14]
Can I use this extension to generate package xml for my production org? Or is it only for sandboxes and DE orgs. Please let me now.

Thank you

**Comment by vignaesh01** [comment]
You can run it on Prod org

**Comment by PreethiThotaMednax** [comment]
Thank you Vignaesh!!

**Comment by vignaesh01** [comment]
closed
