### ISSUE TITLE
Public EmailTemplate and Report missing 

### ISSUE THREAD

**Issue by pcrouzet** [vignaesh01/sfdx-package-generator#16]
When I generate the package.xml selecting the EmailTemplate and Report metadata, all the templates and reports stored on the standard public directory (unfiled$public) are not generated in the package.xml file.

**Comment by vignaesh01** [comment]
The extension uses the "sfdx force:mdapi:listmetadata --json -m  Report"  internally. I guess it is not available as part of the output.

**Comment by venkatesh-ss** [comment]
Hi @pcrouzet, I am also facing the same issue. Did you find any solution for this? I am facing this in MAC systems only. In Windows systems, It is working fine. 

Any thoughts guys?

**Comment by vignaesh01** [comment]
Hi,
Please raise an issue in Salesforce CLI github repo

https://github.com/forcedotcom/cli
