### ISSUE TITLE
Can not specify custom field.

### ISSUE THREAD

**Issue by iamsabbath** [vignaesh01/sfdx-package-generator#18]
It will be very helpfull if users can select custom fields instead of the whole custom object.

**Comment by brettillette** [comment]
It'd definitely be really helpful!

**Comment by aj2taylo** [comment]
+1

**Comment by evanmontigney** [comment]
This is the main issue preventing us from adopting this tool, it would otherwise be perfect for us!

**Comment by vignaesh01** [comment]
Let me start looking into this issue

**Comment by evanmontigney** [comment]
Thanks, you rock! This is a gap with SF's own tools too, and the main one we were combing the available extensions to try and fix.

**Comment by vignaesh01** [comment]
Custom Fields & Validation rules are now available for selection with the later update 1.4.0
