### ISSUE TITLE
Any metadata avaiable for choose

### ISSUE THREAD

**Issue by oriolete** [vignaesh01/sfdx-package-generator#2]
After waiting a long time nothing appears to choose.

I'm running VsCode 1.33 on MacOS X 10.14.4 and Salesforce Extension Pack 45.14.0

Thanks in advance

Dump on Developer Tools:

mainThreadExtensionService.ts:60 [[object Object]]Unexpected end of JSON input
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
mainThreadExtensionService.ts:61 SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at Socket.getMetadataTypes.vscode.window.withProgress.foo.stdout.on (/Users/ofarras/.vscode/extensions/vignaeshrama.sfdx-package-xml-generator-0.0.8/out/extension.js:386)
	at Socket.emit (events.js:187)
	at addChunk (_stream_readable.js:279)
	at readableAddChunk (_stream_readable.js:260)
	at Socket.Readable.push (_stream_readable.js:219)
	at Pipe.onread (net.js:636)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:61
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
4console.ts:134 [Extension Host] SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at Socket.getMetadataTypes.vscode.window.withProgress.foo.stdout.on (/Users/ofarras/.vscode/extensions/vignaeshrama.sfdx-package-xml-generator-0.0.8/out/extension.js:386:37)
	at Socket.emit (events.js:187:15)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:260:13)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
t.log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
mainThreadExtensionService.ts:60 [[object Object]]Unexpected token a in JSON at position 1
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
mainThreadExtensionService.ts:61 SyntaxError: Unexpected token a in JSON at position 1
	at JSON.parse (<anonymous>)
	at Socket.getMetadataTypes.vscode.window.withProgress.foo.stdout.on (/Users/ofarras/.vscode/extensions/vignaeshrama.sfdx-package-xml-generator-0.0.8/out/extension.js:386)
	at Socket.emit (events.js:187)
	at addChunk (_stream_readable.js:279)
	at readableAddChunk (_stream_readable.js:260)
	at Socket.Readable.push (_stream_readable.js:219)
	at Pipe.onread (net.js:636)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:61
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
4console.ts:134 [Extension Host] SyntaxError: Unexpected token a in JSON at position 1
	at JSON.parse (<anonymous>)
	at Socket.getMetadataTypes.vscode.window.withProgress.foo.stdout.on (/Users/ofarras/.vscode/extensions/vignaeshrama.sfdx-package-xml-generator-0.0.8/out/extension.js:386:37)
	at Socket.emit (events.js:187:15)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:260:13)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
t.log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
mainThreadExtensionService.ts:60 [[object Object]]Unexpected token e in JSON at position 0
$onExtensionRuntimeError @ mainThreadExtensionService.ts:60
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
mainThreadExtensionService.ts:61 SyntaxError: Unexpected token e in JSON at position 0
	at JSON.parse (<anonymous>)
	at Socket.getMetadataTypes.vscode.window.withProgress.foo.stdout.on (/Users/ofarras/.vscode/extensions/vignaeshrama.sfdx-package-xml-generator-0.0.8/out/extension.js:386)
	at Socket.emit (events.js:187)
	at addChunk (_stream_readable.js:279)
	at readableAddChunk (_stream_readable.js:260)
	at Socket.Readable.push (_stream_readable.js:219)
	at Pipe.onread (net.js:636)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:61
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
4console.ts:134 [Extension Host] SyntaxError: Unexpected token e in JSON at position 0
	at JSON.parse (<anonymous>)
	at Socket.getMetadataTypes.vscode.window.withProgress.foo.stdout.on (/Users/ofarras/.vscode/extensions/vignaeshrama.sfdx-package-xml-generator-0.0.8/out/extension.js:386:37)
	at Socket.emit (events.js:187:15)
	at addChunk (_stream_readable.js:279:12)
	at readableAddChunk (_stream_readable.js:260:13)
	at Socket.Readable.push (_stream_readable.js:219:10)
	at Pipe.onread (net.js:636:20)
t.log @ console.ts:134
$logExtensionHostMessage @ mainThreadConsole.ts:39
_doInvokeHandler @ rpcProtocol.ts:399
_invokeHandler @ rpcProtocol.ts:384
_receiveRequest @ rpcProtocol.ts:304
_receiveOneMessage @ rpcProtocol.ts:226
_protocol.onMessage.e @ rpcProtocol.ts:101
fire @ event.ts:584
a @ ipc.net.ts:392
e @ ipc.net.ts:399
fire @ event.ts:584
_receiveMessage @ ipc.net.ts:678
_socketDisposables.push._socketReader.onMessage.e @ ipc.net.ts:549
fire @ event.ts:584
acceptChunk @ ipc.net.ts:212
_register._socket.onData.e @ ipc.net.ts:173
t @ ipc.net.ts:24
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636

**Comment by vignaesh01** [comment]
Hi oriolete,
It seems to be an auth error. Before using this extension you need to create a sfdx project with manifest and Authorize it using commands in salesforce extension for vs code suite. This extension works only for org based development model
Refer : [Org Developemt model](https://forcedotcom.github.io/salesforcedx-vscode/articles/user-guide/org-development-model)

If you have already done the above steps, try re authorizing your org using SFDX: Authorize an Org

Do let me if it works

**Comment by oriolete** [comment]
Hi Vignaesh,

I've tried several times as you say Creating Project with Manifest and
Authorizing an Org with same behaviour.

Thanks in advance

**Comment by vignaesh01** [comment]
Hi oriolete,
 I am unable to recreate this issue. So let me include a console.log() statement just before the error line you mentioned and republish the plugin. I will let you know once I do that. That would give some insight. It seems to be the sfdx command running in the background is returning a malformed json.

Meanwhile can you run the below command in your workspace folder and send me the results.
`sfdx force:mdapi:describemetadata --json`

**Comment by oriolete** [comment]
Hi Vignaesh,

tell me to test again with log active.

Attached you can find requested command output.

Thanks

**Comment by vignaesh01** [comment]
Sure @oriolete . I couldn't find any attachments in the comments. Could you please send it again.

**Comment by oriolete** [comment]
Sorry I've used to respond via email but attachment not uploaded to github. 

[vignaesh.log](https://github.com/vignaesh01/sfdx-package-generator/files/3166363/vignaesh.log)

**Comment by vignaesh01** [comment]
I have pushed the latest update with the console log. Please run it now and provide the full log.

**Comment by oriolete** [comment]
You have new log output

[vignaesh.log](https://github.com/vignaesh01/sfdx-package-generator/files/3168088/vignaesh.log)

**Comment by vignaesh01** [comment]
Thanks for the log. I have pushed the fix in version 0.0.10. Please update you extension and let me know.

**Comment by oriolete** [comment]
@vignaesh01 now It works like a charm.

Thanks again
