### ISSUE TITLE
Cannot Specify customField or validationRule. 

### ISSUE THREAD

**Issue by zahraK1** [vignaesh01/sfdx-package-generator#20]
I am unable to specify the customfield or validationRule in the extension. I am unable to migrate that without specifying the object itself, which is very bad practice!! Please add this! 
I currently am using a google extension for workbench to finish the xml. I would much rather use your extension to complete my Xml. 
Please fix this

**Comment by vignaesh01** [comment]
I am currently working on this. This will be available in the next update.

**Comment by vignaesh01** [comment]
Duplicate of #18

**Comment by vignaesh01** [comment]
Custom Fields & Validation rules are now available for selection with the later update 1.4.0
