### ISSUE TITLE
Unable to search for components

### ISSUE THREAD

**Issue by zahraK1** [vignaesh01/sfdx-package-generator#21]
I am unable to search for a component globally. It would be much easier to search for metadata if you included a global search bar at the top that searched through all different components. It would make creating xml a lot faster.

**Comment by zahraK1** [comment]
I am also unable to search on the page either. I can't use ctrl+f to search for items on the page as well on this extension.

**Comment by vignaesh01** [comment]
This will be fixed as part of the UI revamp.

**Comment by vignaesh01** [comment]
This is now available in version 2.9.0
