### ISSUE TITLE
Update Package xml not working 

### ISSUE THREAD

**Issue by knowledgeink** [vignaesh01/sfdx-package-generator#27]
Hello,
Based on the initial instructions, When I select update package xml, nothing happening. Also when i select retrieves its throwing an error 
error deploying or retrieving source: The file or directory that you tried to deploy or retrieve isn't in a package directory that's specified in your sfdx-project.json file. Add this location to your "packageDirectories" value, or deploy or retrieve a different file or directory. For details about sfdx-project.json, see: https://developer.salesforce.com/docs/atlas.en-us.sfdx_dev.meta/sfdx_dev/sfdx_dev_ws_config.htm

**Comment by vignaesh01** [comment]
Hi,
Please share the steps to reproduce and also the error logs. Is the package.xml file available under manifest folder of your project?
