### ISSUE TITLE
Generator is not populating with metadata

### ISSUE THREAD

**Issue by flhhc** [vignaesh01/sfdx-package-generator#29]
When I open the package generator,  it isn't giving me any metadata to select. 
Instead of a list of metadata, it shows nothing to filter.

I have vs code version 1.44.0.
I have uninstalled an reinstalled the package generator and restarted vs code.

**Comment by vignaesh01** [comment]
Hi @flhhc ,
 Please try the following,
1. Update to the latest version of Salesforce package.xml generator extension.
2. Check whether the package.xml is present inside the manifest folder.
3. Reauthenticate your org with your sfdx project

If still the issue persists, please send me the extension logs & developer tools log.

Steps for Extension logs:
Help -> Toggle Developer Tools
View -> Command Palette -> Developer : Open Logs Folder

Steps for Developer tools log:
View -> Command Palette -> Developer : Open Webview Developer Tools

**Comment by flhhc** [comment]
I uninstalled the package generator, then closed vs code.
I installed the package generator and closed vs code.
I re-authenticated to an org and now the generator shows metadata.
Thanks!
