### ISSUE TITLE
Metadata Component chooser should respect existing package.xml

### ISSUE THREAD

**Issue by tet3** [vignaesh01/sfdx-package-generator#3]
When opening the Choose Metadata Components page, the components that are already in `package.xml` should be checked. Currently, you can't use the tool to edit an existing package.xml without re-checking all the elements that were selected before.

**Comment by vignaesh01** [comment]
Hi Thomas,
This is definitely in the pipeline and will be available in future updates

**Comment by vignaesh01** [comment]
Hi @tet3 ,
This one is fixed now with the latest release. Please do check it out.
