### ISSUE TITLE
Select all won't select certain components

### ISSUE THREAD

**Issue by rbeachHYP** [vignaesh01/sfdx-package-generator#38]
When I do a "Select All" I get a message "All metadata selected except..." and there are a few elements listed. If I select those individually I can generate the XML for them but why aren't they included in a Select All?

**Comment by vignaesh01** [comment]
Metadata with folders like reports,email templates are not selected just to save some time during Select All.
Child metadata like custom fields, validation rules are not selected as they are automatically retrieved from their parent Custom object which is selected
