### ISSUE TITLE
Unable to retrieve StandardValueSet from org

### ISSUE THREAD

**Issue by balamurali25** [vignaesh01/sfdx-package-generator#40]
Hello,
Great extension. Thank you!

One thing I noticed today was when trying to retrieve StandardValueSets from the org - the metadata type shows up - but the standard value sets from the org are not coming up in the right pane.

Thank you!

**Comment by vignaesh01** [comment]
Hi @balamurali25 ,
 Thanks for your feedback. The extension internally runs the below command to fetch StandardValueSets

sfdx force:mdapi:listmetadata --json -m StandardValueSet

If this command doesn't return an result, please raise an issue with Salesforce CLI team.
