### ISSUE TITLE
Custom Objects list includes Standard Objects

### ISSUE THREAD

**Issue by stephenpstanley** [vignaesh01/sfdx-package-generator#41]
When you select the Custom Object Metadata types, it also retrieves all Standard Objects

I'm guessing that if you try to deploy a package that includes standard objects that Salesforce will complain.  Can you please allow exclusion of Standard Objects?

**Comment by vignaesh01** [comment]
Hi @stephenpstanley ,
 The extension runs the below command internally while fetching Custom Objects

sfdx force:mdapi:listmetadata --json -m CustomObject

Salesforce returns both standard and custom object as result. Please avoid selecting standard objects or after package.xml generation delete all the standard object references in the file.

**Comment by stephenpstanley** [comment]
I was thinking that a quick fix would be to change the heading to be "all Objects" or if you retain the Custom Object heading to filter for objects using a *__c wildcard (if sfdx allows this of course)
