### ISSUE TITLE
Nothing happens

### ISSUE THREAD

**Issue by ethanone1** [vignaesh01/sfdx-package-generator#44]
After installing and running from command palette, the "Choose Metadata Components" tab opens and i see the message that says "Processing Metadata"but nothing happens after that. There are no results on the left panel, filtering does nothing. What am I missing?

**Comment by Walletau** [comment]
Have the same issue.

**Comment by vignaesh01** [comment]
Hi,
Please try the following,
1. Update to the latest version of Salesforce  generator extension.
2. Check whether the package.xml is present inside the manifest folder.
3. Reauthenticate your org with your sfdx project

If still the issue persists, please send me the extension logs & developer tools log.

Steps for Extension logs:
Help -> Toggle Developer Tools
View -> Command Palette -> Developer : Open Logs Folder

Steps for Developer tools log:
View -> Command Palette -> Developer : Open Webview Developer Tools
