### ISSUE TITLE
Suggestions

### ISSUE THREAD

**Issue by oriolete** [vignaesh01/sfdx-package-generator#5]
Hi Vignaesh,

Can I made you a pair of suggestions? 

First It would be very usefull a "select all" button and next it would be very nice sorted names in each type of metadata.

Thanks in advance.

**Comment by vignaesh01** [comment]
Hi @oriolete ,
Noted. Will work on it. The names in Choose Metadata Components window is already sorted. Do you mean sorting it in package.xml file?

**Comment by oriolete** [comment]
Do you mean sorting it in package.xml file? Yes, sorry for my bad explanations 🤪

**Comment by vignaesh01** [comment]
Hi @oriolete , 
Sorting of package.xml contents is available now in version 1.1.0.

**Comment by oriolete** [comment]
Thanks @vignaesh01, I will try it.

**Comment by ukumarb** [comment]
Hi @vignaesh01 
  My suggestion will be 
  1. To include the search at each parent level next to each metadata type, also at the top level to search the type of metadata types.
  2. To consider one level below from the parent level metadata type like the custom field, validation rules, page layout, workflowrule, workflowFieldUpdate.

**Comment by AndrewNR** [comment]
Hi @vignaesh01,
My suggestion for UI - is this possible to make the panel with buttons to remain as the "page header", and only the components tree panel to be scrollable?

It will allow a user to scroll down to the last metadata type tree node, select it, and there will be no need to scroll back to the top of the extension settings page to click the _"Update Package.xml"_ there. Thanks!

**Comment by peternoges** [comment]
Hi @vignaesh01 cool plugin!!  A suggestion is to allow the VS Code User to specify in User Settings the concept of "Metadata to Skip during SELECT ALL" .   My use-case is that I often want MOST metadata, but there are metadata types that I want to skip that your plugin does not skip,  such as CustomObjectTranslation.    I know I can uncheck them, but it would be nice if I could override the "SELECT ALL"  to be "SELECT ALL EXCEPT XYZ"

**Comment by vignaesh01** [comment]
I will be revamping the UI. All these will be handled as part of it.

**Comment by vignaesh01** [comment]
Search feature is now available in version 2.0.0
