### ISSUE TITLE
The package generator hangs while listing Apex classes

### ISSUE THREAD

**Issue by vcheruku-docmation** [vignaesh01/sfdx-package-generator#7]
Hi, 

Not sure if it related to issue #1 but the listing for ApexClasses hangs when there are a lot of classes in the Org. Other components work fine. I have more than 1900 Apex classes and this seems to hang indefinitely.
the org is not a problem since I can get the complete list from the terminal within VsCode. I do have to either specify the output file or redirect the output to a file to get the full list. 
I am new to VsCode and have not been able to get more information from the log files.

Not sure if there is a configuration to allow large file output in VsCode or the SF CLI.

**Comment by vignaesh01** [comment]
Hi @vcheruku-docmation ,
 Please send me the logs. You can capture logs using the command "Developer : Toggle Developer tools".

**Comment by tsalb** [comment]
I am getting the same thing. Also hangs for CustomMetadata as well.

- [Extension Host] Unable to log remote console arguments Output omitted for a large object that exceeds the limits

- [[object Object]]Unexpected end of JSON input

- SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at ChildProcess.fetchChildren.vscode.window.withProgress.foo.on

**Comment by vcheruku-docmation** [comment]
Apologies for the delay in adding the console output. the errors are the same as what @tsalb reported above.
A little more detail from the Console output. May help in debugging further:

workbench.main.js:238 [Extension Host] exit code null
workbench.main.js:238 [Extension Host] Unable to log remote console arguments Output omitted for a large object that exceeds the limits
workbench.main.js:3241 [[object Object]]Unexpected end of JSON input
$onExtensionRuntimeError @ workbench.main.js:3241
_doInvokeHandler @ workbench.main.js:3293
_invokeHandler @ workbench.main.js:3293
_receiveRequest @ workbench.main.js:3292
_receiveOneMessage @ workbench.main.js:3290
_protocol.onMessage.e @ workbench.main.js:3289
fire @ workbench.main.js:77
a @ workbench.main.js:322
e @ workbench.main.js:322
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:331
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:328
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:325
_register._socket.onData.e @ workbench.main.js:324
t @ workbench.main.js:333
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
workbench.main.js:3241 SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at ChildProcess.fetchChildren.vscode.window.withProgress.foo.on (/Users/docmation012/.vscode/extensions/vignaeshrama.sfdx-package-xml-generator-1.1.0/out/extension.js:281)
	at ChildProcess.emit (events.js:182)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:237)
$onExtensionRuntimeError @ workbench.main.js:3241
_doInvokeHandler @ workbench.main.js:3293
_invokeHandler @ workbench.main.js:3293
_receiveRequest @ workbench.main.js:3292
_receiveOneMessage @ workbench.main.js:3290
_protocol.onMessage.e @ workbench.main.js:3289
fire @ workbench.main.js:77
a @ workbench.main.js:322
e @ workbench.main.js:322
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:331
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:328
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:325
_register._socket.onData.e @ workbench.main.js:324
t @ workbench.main.js:333
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636
7workbench.main.js:238 [Extension Host] SyntaxError: Unexpected end of JSON input
	at JSON.parse (<anonymous>)
	at ChildProcess.fetchChildren.vscode.window.withProgress.foo.on (/Users/docmation012/.vscode/extensions/vignaeshrama.sfdx-package-xml-generator-1.1.0/out/extension.js:281:41)
	at ChildProcess.emit (events.js:182:13)
	at Process.ChildProcess._handle.onexit (internal/child_process.js:237:12)
t.log @ workbench.main.js:238
$logExtensionHostMessage @ workbench.main.js:3215
_doInvokeHandler @ workbench.main.js:3293
_invokeHandler @ workbench.main.js:3293
_receiveRequest @ workbench.main.js:3292
_receiveOneMessage @ workbench.main.js:3290
_protocol.onMessage.e @ workbench.main.js:3289
fire @ workbench.main.js:77
a @ workbench.main.js:322
e @ workbench.main.js:322
fire @ workbench.main.js:77
_receiveMessage @ workbench.main.js:331
S._socketDisposables.push._socketReader.onMessage.e @ workbench.main.js:328
fire @ workbench.main.js:77
acceptChunk @ workbench.main.js:325
_register._socket.onData.e @ workbench.main.js:324
t @ workbench.main.js:333
emit @ events.js:182
addChunk @ _stream_readable.js:279
readableAddChunk @ _stream_readable.js:264
Readable.push @ _stream_readable.js:219
onread @ net.js:636

**Comment by vignaesh01** [comment]
Please check with the latest update to the extension.
