### ISSUE TITLE
Inconsistent sorting of components

### ISSUE THREAD

**Issue by traod** [vignaesh01/sfdx-package-generator#8]
Hi, everytime I add new components (members) to the package.xml, the package.xml is sorted differently. 
It causes issues when commiting the package.xml to a repository, because there are too many changes done to the file.
Could you use the standard Salesforce sorting of types and members so that it is compatible with other tools on the market? Or at least consistent sorting?
Thank you very much.

This is great extension. Good job.

**Comment by vignaesh01** [comment]
Thanks @traod . This will be fixed in forthcoming releases.

**Comment by vignaesh01** [comment]
This has been fixed in version 1.1.0
